
CLM = /Users/joshua/Documents/Code/clean2/bin/clm
INCLUDES = -I /Users/joshua/Documents/Code/clean2/lib/StdLib -I /Users/joshua/Documents/Code/clean2/lib/Generics

a : skeleton3a.icl
	$(CLM) -ns -fusion $(INCLUDES) skeleton3a -o a

b : skeleton3b.icl
	$(CLM) -ns -fusion $(INCLUDES) skeleton3b -o b