
CLM = /Users/joshua/Documents/Code/clean2/bin/clm
INCLUDES = -I /Users/joshua/Documents/Code/clean2/lib/StdLib -I /Users/joshua/Documents/Code/clean2/lib/Generics
FLAGS = -ns -fusion -h 300M

monadicSemantics : monadicSemantics.icl
	$(CLM) $(FLAGS) $(INCLUDES) monadicSemantics -o monadicSemantics
